defaults:
  - pick_place_human_cart
  - _self_

env_id: HumanObjectInspectionCart
human_animation_names:
  - ObjectInspection/0
  - ObjectInspection/1
  - ObjectInspection/2
  - ObjectInspection/3
  - ObjectInspection/4
  - ObjectInspection/5
  - ObjectInspection/6
  - ObjectInspection/7
object_at_target_reward: -1
goal_exit_tolerance: 0.02
n_animations_sampled_per_100_steps: 2
n_object_placements_sampled_per_100_steps: 3
object_placement_initializer: null