defaults:
  - pick_place_human_cart
  - _self_

env_id: PickPlacePointingHumanCart
human_animation_names:
  - PickPlacePointingHuman/0
  - PickPlacePointingHuman/1
n_object_placements_sampled_per_100_steps: 3
object_placement_initializer: null
