defaults:
  - default/pick_place_pointing_human_cart@_here_
  - _self_

robot_base_offset:
  - 0.0
  - 0.0
  - 0.0
use_camera_obs: false
use_object_obs: true
collision_reward: 0
has_offscreen_renderer: false
render_camera: null
horizon: 500
hard_reset: false
done_at_collision: false
done_at_success: false
