robot_name: modrob1

nb_joints: 6

transformation_matrices: [
  1, 0, 0, 0, 
  0, 1, 0, 0, 
  0, 0, 1, 0.1, 
  0, 0, 0, 1, 
  -2.051e-10, 1, 0, 0, 
  2.051e-10, 4.2067e-20, 1, -0.0655, 
  1, 2.051e-10, -2.051e-10, 0.2362, 
  0, 0, 0, 1, 
  -2.051e-10, 1, 0, 0.4, 
  1, 2.051e-10, 4.1021e-10, 0, 
  4.1021e-10, 8.4135e-20, -1, 0.1353, 
  0, 0, 0, 1, 
  1, 0, 0, 0.114, 
  0, -2.051e-10, 1, 0.047, 
  0, -1, -2.051e-10, 0.1746, 
  0, 0, 0, 1, 
  1, 0, 0, 0, 
  0, -2.051e-10, -1, 0.065, 
  0, 1, -2.051e-10, 0.3776, 
  0, 0, 0, 1, 
  2.051e-10, -2.051e-10, 1, -0.06, 
  -1, 4.1021e-10, 2.051e-10, 0.063, 
  -4.1021e-10, -1, -2.051e-10, 0.06155, 
  0, 0, 0, 1] 

tool_transformation_matrix: [
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 1, 0.119550,
  0, 0, 0, 1]

enclosures: [
  0.00044198, -0.046902, 0.2161,
  0.00056332, -0.039613, 0.20926,
  0.12876,
  0.040556, -0.0014755, 0.13508,
  0.35933, 0.0010087, 0.10717,
  0.13548,
  0.022975, 0.032934, 0.16816,
  0.090252, 0.073889, 0.18217,
  0.12315,
  -1.6823e-05, 0.029956, 0.18763,
  1.6223e-05, 0.069714, 0.35292,
  0.13267,
  -0.045293, 0.032286, 0.091406,
  -0.045293, 0.032286, 0.091406,
  0.12766,
  -4.5649e-05, -9.1593e-16, 0.23055, # We manually set the z-position to 0.23055!
  4.5649e-05, 9.1593e-16, 0.27055,
  0.046807]